---
- name: Playbook to check periodically WoD frontend
  hosts: all
  gather_facts: true
  tasks:
    - name: Ensure that this a compliant WoD system
      ansible.builtin.include_tasks: "{{ WODINSANSDIR }}/check_system.yml"

    - name: Setup frontend ufw firewall TCP rules
      become: true
      become_user: root
      community.general.ufw:
        rule: allow
        port: "{{ WODFEPORT }}"
        proto: tcp
        state: enabled
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_major_version >= "20"

    - name: Setup firewalld TCP rules
      become: true
      become_user: root
      ansible.posix.firewalld:
        port: "{{ WODFEPORT }}/tcp"
        permanent: true
        state: enabled
      when:
        - ansible_distribution == "CentOS" or ansible_distribution == "Rocky"

    - name: Find WoD frontend branded files
      ansible.builtin.find:
        paths: "{{ WODFEDIR }}"
        file_type: file
        use_regex: true
        patterns: ['^.*.j2$']
        recurse: true
        excludes: data
      register: fetemplates

    - name: Copy WoD frontend branded files as ansible template for variable expansion
      ansible.builtin.template:
        src: "{{ item.path }}"
        dest: "{{ item.path | regex_replace('.j2$') }}"
        mode: "0644"
      with_items: "{{ fetemplates.files }}"

    - name: Test private tasks YAML file
      ansible.builtin.command: ls "{{ WODANSIBLEPRIVDIR }}/check_frontend.yml"
      register: acj_path
      failed_when: false
      changed_when: false

    - name: Now call private tasks if available
      ansible.builtin.include_tasks: "{{ WODANSIBLEPRIVDIR }}/check_frontend.yml"
      when:
        - acj_path.rc == 0

    - name: Enable WoD services
      become: true
      become_user: root
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: true
        enabled: true
        name: "{{ item }}"
      with_items:
        - wod-npm-app
